### ISSUE TITLE
Compatibility with Debian 11

### ISSUE THREAD

**Issue by cdoublev** [puppetlabs/puppetlabs-mysql#1492]
## Describe the Bug

The following error appears when Puppet applies the manifest to install MySQL: 

> `Error: Parameter command failed on Exec[datadir-managed_dir-mkdir]: Command must be a String, got value of class Array (file: /tmp/vagrant-puppet/environments/development/modules/mysql/manifests/server/config.pp, line: 47)`

It occurs since [this commit](https://github.com/puppetlabs/puppetlabs-mysql/commit/1c1291d27883fc41eab666eb65f3c85071d6c696) because `Exec.command` does not accept an Array in Puppet v5, which is the version installed from the official repository for Debian 11.

I know that `metadata.json` defines `"version_requirement": ">= 6.0.0 < 8.0.0"` but I did not succeed to install Puppet v6 or v7 on Debian 11, by following [this documentation](https://puppet.com/docs/puppet/7/install_puppet.html#enable_the_puppet_platform_apt) because it seems to only allows installing `puppet-agent` or `puppetserver` v7: it does not install the v7 of Puppet "platform" (with commande line tools, I guess).

As it can be observed from the above output, I use Vagrant, Puppet, and this module, to provision a Debian 11 guest machine with `puppet apply` (run by Vagrant). I am not experienced with serious deployment architectures so please forgive me if there is an obvious solution to get the latest Puppet version running on Debian 11.

## Expected Behavior

I expect compatibility with Debian 11 and the Puppet version provided by the official Debian repository.

## Steps to Reproduce
1. Install puppet on Debian 11
2. Create a manifest file that install MySQL using this module
3. Install the resources using `puppet apply`

## Environment
 - Version: 13
 - Platform: Debian 11

## Additional Context

As a temporary workaround, I downgraded the installed version with `mod 'puppetlabs/mysql', '12.0.2'` in the `Puppetfile`.

**Comment by duritong** [comment]
Puppet version 5 is EOL for a long time: https://puppet.com/docs/puppet/7/platform_lifecycle.html#about_agent

What `puppet-agent` provides you is what you would expect as v7 of Puppet "platform" and it is installable on Debian 11.

Modules have a compatibility with puppet versions AND Operating Systems. You can always use an older version of this module that is compatible with your Puppet version in question.

**Comment by cdoublev** [comment]
> Puppet version 5 is EOL for a long time: https://puppet.com/docs/puppet/7/platform_lifecycle.html#about_agent
> 
> What `puppet-agent` provides you is what you would expect as v7 of Puppet "platform" and it is installable on Debian 11.

Thanks. I could not find this information the last time I installed `puppet-agent`:

> `puppet-agent`: This package contains Puppet’s main code and all of the dependencies needed to run it, including Facter, Hiera, the PXP agent, root certificates, and bundled versions of Ruby and OpenSSL. After it’s installed, you have everything you need to run the Puppet agent service and the `puppet apply` command.

The following comes from your above link, which is about version EOLs. And I did not noticed that installing `puppet-agent` does not automatically export the `puppet` command path... Therefore the commande were not found when running `puppet --version`. 

Anyway, nothing `puppetlabs-mysql` can do about.
