### ISSUE TITLE
Path validation of sql parameter in mysql::db too restrictive.

### ISSUE THREAD

**Issue by rwf14f** [puppetlabs/puppetlabs-mysql#1499]
## Describe the Bug

The regex that is used by `mysql::db` to validate the `sql` parameter refuses to accept perfectly valid pathnames, eg it only accepts a single dot to separate the filename from the extensions, but not anywhere else in the path. In our case it's the powerdns mysql schema path that it's choking on: _/usr/share/doc/pdns-backend-mysql-4.1.14/schema.mysql.sql_.

Is there a reason why the module doesn't use the types from stdlib (`Optional[Array[Stdlib::Unixpath]] $sql = undef,`)? The module has a dependency on it already. Are you worried about whitespaces in paths ?

## Expected Behavior

The module should allow all valid paths.

## Steps to Reproduce

Use paths with a multiple dots in sql parameter.

## Environment
 - Version [13.0.0]
 - Platform [CentOS 7]

**Comment by LukasAud** [comment]
This issue has been addressed in this PR https://github.com/puppetlabs/puppetlabs-mysql/pull/1505

@rwf14f Can you confirm if this a valid solution for the issue?

**Comment by rwf14f** [comment]
Yes, it is. The updated regex validates my use cases correctly now.

**Comment by TwizzyDizzy** [comment]
Hi folks,

TBH, I think that the elephant in the room hasn't been properly answered:

> Is there a reason why the module doesn't use the types from stdlib (Optional[Array[Stdlib::Unixpath]] $sql = undef,)? The module has a dependency on it already. Are you worried about whitespaces in paths ?

Cheers
Thomas
