### ISSUE TITLE
exec failure for puppet < 6.24

### ISSUE THREAD

**Issue by trefzer** [puppetlabs/puppetlabs-mysql#1518]
## Describe the Bug
for puppet < 6.24 this module fails with error:
`Error: Failed to apply catalog: Parameter command failed on Exec[wait_for_mysql_socket_to_open]: Command must be a String, got value of class Array (file: /etc/puppetlabs/code/environments/dev_test/modules/mysql/manifests/server/service.pp, line: 57)`

## Expected Behavior
not failing !

## Steps to Reproduce
puppet below 6.24

## Analysis
The following commits added exec parameters as an Array which is not supported before [puppet 6.24 (release notes)](https://puppet.com/docs/puppet/6/release_notes_puppet.html#unique_1428117924)
* cdaa8393e3fe9b8f971945ee8cb1f3e933902a0d
* 1c1291d27883fc41eab666eb65f3c85071d6c696
* 90168d93834f329ca037f83bedc5b5e580955fb6

## Solution:
Either revert the usage of arrays in exec or raise puppet version needed (client version !) in metadata.json

**Comment by pmcmaw** [comment]
Thank you for logging this issue @trefzer, we have resolved this issue and cut a release.
