### ISSUE TITLE
Manage /var/log/mysql on Debian

### ISSUE THREAD

**Issue by jcharaoui** [puppetlabs/puppetlabs-mysql#1566]
## Use Case

On Debian 12 (bookworm), the `/var/log/mysql` is [not created by the package anymore](https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/ee379fcbdc363b42efa042c4225ed158fe184c02).

Since this module sets `log-error` by default to `/var/log/mysql/error.log`, the absence of the parent directory is causing a failure.

## Describe the Solution You Would Like

Please adjust the module to manage the `/var/log/mysql` directory when `log-error` is being used. This solution should be compatible with all supported versions of Debian.

## Describe Alternatives You've Considered

A workaround is to override `log-error` to `undef`.

**Comment by CamZie** [comment]
Same issue here.

As a workaround I added the following inside `if $options['mysqld']['log-error'] { }` /  `line 24` in the file `manifests/server/installdb.pp` to ensure that the directory exists:

 ```
     file { '/var/log/mysql':
        ensure => 'directory',
        mode   => '0755',
      }
```

**Comment by ajdelgado** [comment]
This add a duplicate resource definition:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/var/log/mysql] is already declared at (file: /etc/puppetlabs/code/environments/production/modules/mysql/manifests/server/managed_dirs.pp, line: 37); cannot redeclare (file: /etc/puppetlabs/code/environments/production/modules/mysql/manifests/server/installdb.pp, line: 34) (file: /etc/puppetlabs/code/environments/production/modules/mysql/manifests/server/installdb.pp, line: 34, column: 5)

**Comment by ottok** [comment]
Seems your solution was to put back the legacy behavior:

    file { $log_dir:
      ensure => 'directory',
      owner  => $mysqluser,
      group  => $mysql::server::mysql_group,
    }

This was removed upstream as Linux distros have moved to use journald. Wouldn't the ideal solution in Puppet be to also use journald instead of diverging and maintaining legacy plain file logging?

**Comment by ottok** [comment]
This bug is still open in Debian as there is no sign that upstream fixed it: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1032407

When closing bugs please include a reference to a commit id or some justification why an issue was closed..
