### ISSUE TITLE
Release page "Full Changeling" link inoperable

### ISSUE THREAD

**Issue by Jericon** [puppetlabs/puppetlabs-mysql#1615]
The link in releases for the full changelog is hitting a 404.  

Releases Page: https://github.com/puppetlabs/puppetlabs-mysql/releases
Full Changelog Link: https://github.com/puppetlabs-mysql/puppetlabs/compare/d28f0e0327d73dde80331494d2abb5562d0ff144...v15.0.0

**Comment by h0tw1r3** [comment]
The changelog generator currently has a bug that does not observe the previous tag.
https://github.com/chelnak/gh-changelog/issues/144

Manually corrected release notes for v15.0.0.
