### ISSUE TITLE
inheritance hell - can not include mysql & mysql::server on the same node

### ISSUE THREAD

**Issue by jhoblitt** [puppetlabs/puppetlabs-mysql#254]
`mysql::server` inherits from `mysql` which can/will cause duplicate class `mysql` declaration errors on nodes that include both `mysql` and `mysql::server`, depending on the exact parse order of the particular manifest.  @apenney promised to fixed this in `#puppet` and to include a ponie in the module.

--reference 5e47aff57ab17946b624be8e8196726c9639acb0

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
