### ISSUE TITLE
mysql_secure_installation

### ISSUE THREAD

**Issue by hunner** [puppetlabs/puppetlabs-mysql#275]
Via email:

> It would be really nice if this module would have the functionality of the /usr/bin/mysql_secure_installation (Debian+Ubuntu I think) integrated. This basically secures a MySQL server on Debian and Ubuntu.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
