### ISSUE TITLE
Removed .my.cnf = errors

### ISSUE THREAD

**Issue by wgregorian** [puppetlabs/puppetlabs-mysql#294]
If for any reason .my.cnf is removed (after it's initially created), the following error comes up on the next run: 

> err: Could not prefetch mysql_user provider 'mysql': Execution of '/usr/bin/mysql -NBe SELECT CONCAT(User,
> '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost'
> (using password: NO)
> 
> err: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]/ensure: change from absent to present failed: Execution of '/usr/bin/mysql -e GRANT USAGE ON _._ TO 'root'@'localhost' IDENTIFIED BY PASSWORD '*0C0391BC20C40E95784D0BB5BB7216D8ADBCC17F' WITH MAX_USER_CONNECTIONS 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_QUERIES_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
