### ISSUE TITLE
Removing anonymous accounts with account_security.pp

### ISSUE THREAD

**Issue by sagepe** [puppetlabs/puppetlabs-mysql#310]
I've got a ::mysql::server class declared which includes "remove_default_accounts => 'true'" thus activating account_security.pp.

This removes most of what I would expect except for the anonymous accounts for ''@'localhost' and ''@'fqdn', although I don't get an error applying the configuration. I've checked inside account_security.pp and it does appear to be attempting to remove these accounts.

I've tested this by removing "remove_default_accounts => 'true'" and adding a dedicated  mysql_user for '@localhost' and setting "ensure=>absent" and see the same behaviour - the configuration gets applied without error but the user remains.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
