### ISSUE TITLE
mysql::server::backup and --flush-logs and empty dump file

### ISSUE THREAD

**Issue by hostingnuggets** [puppetlabs/puppetlabs-mysql#311]
Running Debian 7 here and using the mysql::server::backup to automate backups of my MySQL server. Unfortunately it does not work, I get an empty dump file. Looking at the mysqlbackup.sh script I noticed that if I run the same dump without the "--flush-logs" the dump works.

As such I think it would be nice to have an option in the module to disable this "--flush-logs" parameter.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
