### ISSUE TITLE
mysql_grant is not idempotent 

### ISSUE THREAD

**Issue by gildas** [puppetlabs/puppetlabs-mysql#314]
when used as a standalone type or from mysql::db, mysql_grant will always grant the permissions even if these permissions are already granted.
As a consequence, the node is marked as "changed" in Dashboard or any other reporting tool.

mysql_grant should check the permissions first, and grant the new ones only if they are not already granted.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
