### ISSUE TITLE
the flag `remove_default_accounts` appears to do nothing

### ISSUE THREAD

**Issue by spuder** [puppetlabs/puppetlabs-mysql#323]
If you call the mysql::server class with the remove_default_accounts flag, you are still able to log in anonymously which leads the user to believe it did not work. 

class { '::mysql::server':
  root_password   => 'foo',
  remove_default_accounts => true,
  restart                 => true,
}

This spawned two questions: 

http://dba.stackexchange.com/questions/51452/how-do-you-disable-anonymous-login-mysql/51455#51455

https://ask.puppetlabs.com/question/3662/disable-mysql-anonymous-accounts/?answer=3664

In actuality, remove_default_accounts does work, but because the password is stored in /root/.my.cnf the user can be led to believe that accounts without passwords still exist. 

**Solution**:
Add a warning to the README.MD outlying this pitfall. Even if anonymous accounts are disabled, the root user will still _appear_ to have password less logins.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
