### ISSUE TITLE
mysql_grant being called again on each puppet update

### ISSUE THREAD

**Issue by hostingnuggets** [puppetlabs/puppetlabs-mysql#324]
I am using the latest version 2.0-rc5 and have the problem where my mysql_grant gets called on each update which somehow means that the mysql module does not recognise that it already applied this grant.

Below is the relevant part of my manifest:

``` puppet
    mysql_user { "${username}@${hostname}":
        ensure          => 'present',
        password_hash   => $password,
    }

    mysql_grant { "${username}@${hostname}/*.*":
        ensure          => 'present',
        options         => ['GRANT'],
        privileges      => ['CREATE USER','ALTER','CREATE','DELETE','DROP','INDEX','INSERT','SELECT','UPDATE','LOCK TABLES','CREATE VIEW','SHOW VIEW','ALTER ROUTINE','CREATE ROUTINE','EXECUTE'],
        table           => '*.*',
        user            => "${username}@${hostname}",
    }
```

is this a bug or am I doing something wrong here?

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
