### ISSUE TITLE
Could not prefetch mysql_grant provider

### ISSUE THREAD

**Issue by walterheck** [puppetlabs/puppetlabs-mysql#329]
I get this message on a puppet run:

Error: Could not prefetch mysql_grant provider 'mysql': Execution of '/usr/bin/mysql --defaults-file=/root/.my.cnf -NBe SHOW GRANTS FOR 'root'@'yomamma';' returned 1: ERROR 1141 (42000) at line 1: There is no such grant defined for user 'root' on host 'yomamma'

Some info from mysql:

MariaDB [(none)]> select user, host from mysql.user;
+------------------+-----------+
| user             | host      |
+------------------+-----------+
| root             | 127.0.0.1 |
| root             | ::1       |
| root             | yomama    |
| debian-sys-maint | localhost |
| mmm_agent        | localhost |
| mmm_monitor      | localhost |
| mmm_reader       | localhost |
| mmm_writer       | localhost |
| replication      | localhost |
| root             | localhost |
+------------------+-----------+
10 rows in set (0.00 sec)

MariaDB [(none)]> SHOW GRANTS FOR 'root'@'yomamma';
ERROR 1141 (42000): There is no such grant defined for user 'root' on host 'yomamma'
MariaDB [(none)]> SHOW GRANTS FOR `root`@`yomamma`;
ERROR 1141 (42000): There is no such grant defined for user 'root' on host 'yomamma'
MariaDB [(none)]> SHOW GRANTS FOR root@yomamma;
ERROR 1141 (42000): There is no such grant defined for user 'root' on host 'yomamma'
MariaDB [(none)]> SHOW GRANTS FOR root@`127.0.0.1`;
+----------------------------------------------------------------------------------------------------------------------------------------+
| Grants for root@127.0.0.1                                                                                                              |
+----------------------------------------------------------------------------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON _._ TO 'root'@'127.0.0.1' IDENTIFIED BY PASSWORD '*D1A4CE85A15D483A108CE9908404169874531C50' WITH GRANT OPTION |
+----------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MariaDB [(none)]> show global variables like '%resolve%';
+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| skip_name_resolve | ON    |
+-------------------+-------+
1 row in set (0.00 sec)

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
