### ISSUE TITLE
"Could not prefetch"… Where to specify root password?

### ISSUE THREAD

**Issue by sebastiaanluca** [puppetlabs/puppetlabs-mysql#331]
I have now encountered these errors on two different production servers, always when there already was a mysql service defined (but not via Puppet).

```
err: Could not prefetch mysql_database provider 'mysql': Execution of '/usr/bin/mysql -NBe show databases' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

err: Could not prefetch mysql_grant provider 'mysql': Execution of '/usr/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

err: Could not prefetch mysql_user provider 'mysql': Execution of '/usr/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

I have tried specifying the root password in the following ways:

``` ruby
class { 'mysql::server':
    old_root_password => 'password',
    root_password => 'password',
    override_options => { root_password => 'password' }
}
```

Neither seems to work. As of yet, I have not been successful in using this package. The documentation isn't quite clear on this, or I'm just misinterpreting them.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
