### ISSUE TITLE
Add privileges parameter to mysql::server::monitor class

### ISSUE THREAD

**Issue by hostingnuggets** [puppetlabs/puppetlabs-mysql#337]
I am using the mysql::server::monitor class to add a monitoring user to my MySQL server in order to get it monitored by nagios. This monitoring user gets automatically the PROCESS and SUPER privileges, in my case using nagios, I do not require any of these privileges. 

As such I think it would be really nice to add a 4th option the the mysql::server::monitor class such as mysql_monitor_privileges where one could add custom privileges. In my case I would simply pass an empty array [] to give no privileges. Nagios just connects and disconnects to see if the server is up and running.

What do you think?

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
