### ISSUE TITLE
Imho it's not possible to explicitly disable ssl.

### ISSUE THREAD

**Issue by spielkind** [puppetlabs/puppetlabs-mysql#338]
I want to disable (remove) ssl in the my.cnf. 
I tried to set it to "false" or "0" with override_options, also i tried to set "skip-ssl" but nothing worked, can somebody point me to the correct option?

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
