### ISSUE TITLE
mysql::server::backup should require mysql::server::service

### ISSUE THREAD

**Issue by johnclarson** [puppetlabs/puppetlabs-mysql#347]
On initial deployment, the mysql::server::backup class fails because mysqld is not running when it attempts to create the backup user.

I was able to fix this by adding a require to the backup.pp for the $backupuser.

``` puppet
mysql_user { "${backupuser}@localhost":
  ensure        => $ensure,
  password_hash => mysql_password($backuppassword),
  provider      => 'mysql',
  require       => [
    Class['mysql::server::config'],
    Class['mysql::server::service']
  ],
}
```

I can submit if you like

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
