### ISSUE TITLE
Proposal mysql_user and mysql_grant

### ISSUE THREAD

**Issue by vicinus** [puppetlabs/puppetlabs-mysql#360]
The following proposed changes will break mysql_user and mysql_grant for existing configurations, but in my opinion the changes will improve the code:

1.)  Make every privilege (including the GRANT OPTION privilege) a separate parameter of type boolean.
2.) Move the global privileges (CREATE USER, FILE, PROCESS, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHUTDOWN, and SUPER) which can only be set on the user level to mysql_user
3.) Throw puppet errors on catalog creation, instead of mysql errors on catalog execution, if on table level privileges are tried to set, which are only allowed on database or user level.
4.) Get rid of the special title requirement for mysql_grant

I'm willing to work on this changes if a reasonable change exists that they are accepted.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
