### ISSUE TITLE
Duplicate defaults-file definition in providers

### ISSUE THREAD

**Issue by w32-blaster** [puppetlabs/puppetlabs-mysql#370]
In mysql_\* providers the "self.defaults_file" methods are duplicated and should be removed. All mysql_\* provider includes (except mysql_grant which should be fixed also) the main mysql.rb file in which the "self.defaults_file" method already exists.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
