### ISSUE TITLE
Add REQUIRE options for SSL

### ISSUE THREAD

**Issue by srinathman** [puppetlabs/puppetlabs-mysql#371]
REQUIRE can bet set for ssl connections and authentication as defined in:

http://dev.mysql.com/doc/refman/5.1/en/grant.html

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:

**Comment by theo546** [comment]
Hello, I see that this issue was closed without the feature being implemented, did we missed anything?

If not, could you reopen the issue?
