### ISSUE TITLE
Proposal Moving .my.cnf file out from root folder

### ISSUE THREAD

**Issue by w32-blaster** [puppetlabs/puppetlabs-mysql#373]
At the moment the defaults-extra-file parameter in the providers is looking for the .my.cnf file in root home (-defaults-extra-file=#{Facter.value(:root_home)}/.my.cnf) which is definitely useless because mysql is automatically checking for this file in the home folder of user running puppet process. 

My proposal is to move the .my.cnf file to /etc/puppet/mysql.cnf or to a similar location, so we have a redundant setup. In case if the file on the newplace is missing, mysql still tries to look for it in home folder.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
