### ISSUE TITLE
mysql_grant is not working for grants on a PROCEDURE

### ISSUE THREAD

**Issue by tekenny** [puppetlabs/puppetlabs-mysql#378]
I tried to reverse engineer the proper syntax for to setup a grant on a procedure. My DBA set it up and I then performed "puppet resource mysql_grant" which provided a resource definition similar to below

``` puppet
mysql_grant { "repgen@localhost/PROCEDURE ${dbName}.my_proc":
  ensure     => present,
  options    => ['GRANT'],  
  privileges => ['EXECUTE'],
  table      => "PROCEDURE ${dbName}.my_proc",
  user       => 'repgen@localhost',
  require    => Service['mysqld'],
}
```

However applying it causes the following error

```
Error: Execution of '/usr/bin/mysql -e GRANT EXECUTE ON `PROCEDURE rdb`.my_rpoc TO 'repgen'@'localhost'' returned 1: ERROR 1144 (42000) at line 1: Illegal GRANT/REVOKE command; please consult the manual to see which privileges can be used
```

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
