### ISSUE TITLE
Old database_* providers

### ISSUE THREAD

**Issue by w32-blaster** [puppetlabs/puppetlabs-mysql#383]
There are any reasons why the old providers (with name database, database_grant, database_user) still exist in the project? Maybe I miss some point but I can't see any reason why we should keep this providers. 

Tamas

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
