### ISSUE TITLE
Request: Rename root

### ISSUE THREAD

**Issue by Stofkn** [puppetlabs/puppetlabs-mysql#389]
Hello

I want to rename root to zorro for example, is it already possible with this module?
I took a fast look at the module but in templates/my.cnf.pass.erb I saw user=root. 
Is there a way to provide the username as an argument?

Kind regards

Kristof

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
