### ISSUE TITLE
mysql::params uses incorrect syntax

### ISSUE THREAD

**Issue by danielfoglio** [puppetlabs/puppetlabs-mysql#396]
mysql::params uses incorrect syntax for the 'log-error' and 'pid-file' options('log_error' and 'pid_file') rendered in /etc/my.cnf .  These need to be corrected to ensure people using the module use the correct syntax when attempting to override defaults in mysql::server override_options and not the incorrect syntax in mysql::params.
Pull request #394 and commit sha: dc40b0e01f568cb41cfa8b25de92a0a0fd4d5a17 fix this.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
