### ISSUE TITLE
resources resource purge deletes system databases (mysql, [information|performance]_schema)

### ISSUE THREAD

**Issue by srinathman** [puppetlabs/puppetlabs-mysql#399]
The system databases should always be managed to avoid them to be purged when using resources resource

Ex:

``` puppet
resources { 'mysql_database-${fqdn}':
  name  => 'mysql_database',
  purge => true,
}
```

This would purge (or try to) mysql, information_schema and perfornance_schema DATABASES

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
