### ISSUE TITLE
module does not work with reports for the puppet-dashboard 

### ISSUE THREAD

**Issue by hostingnuggets** [puppetlabs/puppetlabs-mysql#404]
I am using puppet-dashboard and as such sending the puppet agent reports to it. On the nodes where I use this mysql module, puppet is not able to send the reports to the puppet master:

puppet-agent[4111]: Could not send report: Error 400 on SERVER: (<unknown>): found character that cannot start any token while scanning for the next token at line 921 column 14

any ideas what could be wrong here? the error messages supposes maybe a formatting error in YAML

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
