### ISSUE TITLE
override_options does not toggle service restart

### ISSUE THREAD

**Issue by rlex** [puppetlabs/puppetlabs-mysql#406]
(trunk)
I tried setting bind address for mysql server like this

``` puppet
class { 'mysql::server':
  override_options => {
    'mysqld'      => {
      'bind-address' => '0.0.0.0',
    },
  }
}
```

Config successfully edited with proper params, but service does not receive notification and does not restarting.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
