### ISSUE TITLE
request/proposal: configurable mysql root my.cnf location

### ISSUE THREAD

**Issue by bpesics** [puppetlabs/puppetlabs-mysql#414]
in order to be able to manage remote and multiple mysql server instances the location of the mysql root my.cnf file should be configurable

my exact use case is managing many AWS RDS instances from one machine (masterless puppet apply ...), which is not possible due to the hard coded my.cnf path

e.g. i'd like to specify /etc/x/rdsX.fqdn.my.cnf for rdsX.fqdn in the rdsX.pp

(see issue #373)

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
