### ISSUE TITLE
We need a way to distinguish between MySQL versions and different flavours

### ISSUE THREAD

**Issue by igalic** [puppetlabs/puppetlabs-mysql#417]
There are currently n different Flavours of MySQL: Oracle, Drizzle, Percona, MariaDB.
They come with different capabilities, but we're currently using a common denominator which is slowly getting out of date as new features are added to these forks.

We should add a fact to distinguish the version and flavour of MySQL we're dealing with.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
