### ISSUE TITLE
Unable to create a database without creating a new user for it.

### ISSUE THREAD

**Issue by deinspanjer** [puppetlabs/puppetlabs-mysql#430]
I originally tried to invoke mysql::server with no root password and parameters to create a user "tester" with grants to _._.
When I attempted to create a new database with the sql paramter (requiring the use of the mysql::db command later down the manifest after the SQL file had been provisioned), I couldn't pass in the tester user because it stated the user was already defined.  I tried to pass in "root" with no password, and that somehow changed the root user where I could no longer log in at all and puppet would error out whenever attempting to provision anything.

Please forgive me if it is already possible to do what I'm wanting to do and I just didn't understand the syntax.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
