### ISSUE TITLE
Dynamic lookup of mysql param variables deprecated.

### ISSUE THREAD

**Issue by andrewkew** [puppetlabs/puppetlabs-mysql#431]
Hi

I am getting the following error when trying to install mysql server via puppet

```
warning: Dynamic lookup of $mysql::params::client_package_ensure at /etc/puppet/modules/mysql/manifests/client.pp:4 is deprecated. For more information, see http://docs.puppetlabs.com/guides/scope_and_puppet.html. To see the change in behavior, use the --debug flag.

Parameter ensure failed: Invalid value "". Valid values are present, absent, purged, held, latest. Valid values match /./. at /etc/puppet/modules/mysql/manifests/client/install.pp:6
```

Here is the file

``` puppet
 #
 class mysql::client (
   $bindings_enable = $mysql::params::bindings_enable,
   $package_ensure  = $mysql::params::client_package_ensure,
   $package_name    = $mysql::params::client_package_name,
 ) inherits mysql::params {
```

I have read the documentation on changes to variable scope but this looks to be adhering to these changes as the variables are being used with their namespace so doesn't make sense what the problem is.

I have this running on Ubuntu Server 13.04 with puppet 2.7.18

Thanks
Andrew

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
