### ISSUE TITLE
charset and collate keep changing on all puppet runs

### ISSUE THREAD

**Issue by juanbrein** [puppetlabs/puppetlabs-mysql#434]
### Behavior:

puppet code:

``` puppet
  class { '::mysql::server':
    override_options => { 
      'mysqld' => { 
         'max_connections'       => '1024',
      } 
    } 
  } 

  mysql::db { 'mydb':
    user     => 'myuser',
    password => 'mypass',
    host     => 'localhost',
    grant    => ['SELECT', 'UPDATE'],
  }

```

Multiple puppet runs will always report:

```
Notice: /Stage[main]/Test/Mysql::Db[mydb]/Mysql_database[mydb]/charset: charset changed 'latin1' to 'utf8'
Notice: /Stage[main]/Test/Mysql::Db[mydb]/Mysql_database[mydb]/collate: collate changed 'latin1_swedish_ci' to 'utf8_general_ci'
```
### Workaround

Declare mysql server with utf8 as default character set:

``` puppet
  class { '::mysql::server':
    override_options => {
      'mysqld' => {
         'max_connections'       => '1024',
         'default-character-set' => 'utf8'
      }
    }
  }
```
### Cause:

When building the attributes hash , is running show variables like %_database without selecting the database. That report default charset value not  per database value

```
lib/puppet/provider/mysql_database/mysql.rb:10

 10       mysql([defaults_file, '-NBe', "show variables like '%_database'"].compact).split("\n").each do |line|

```

I can submit a pull request if needed with this bug.

Cheers

Juan Breinlinger
Breins.net

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
