### ISSUE TITLE
mysql::bindings doesn't use containment for its subclasses

### ISSUE THREAD

**Issue by deinspanjer** [puppetlabs/puppetlabs-mysql#437]
I've been troubleshooting some dependency order issues with a Vagrant provisioning project.
https://gist.github.com/deinspanjer/8696148
In this gist, I see that the Mysql::Bindings::Java resource logs its finish before the Mysql::Server or Java resources do.

Does that mean that the bindings were actually installed before Java or MySQL server, despite:
require     => [ Class["java"], Class["::mysql::server"] ],

?

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
