### ISSUE TITLE
error in issuiing SQL on database creation

### ISSUE THREAD

**Issue by gioppoluca** [puppetlabs/puppetlabs-mysql#438]
on db.pp we have this code

``` puppet
    if $sql {
      exec{ "${name}-import":
        command     => "/usr/bin/mysql ${name} < ${sql}",
        logoutput   => true,
        refreshonly => $refresh,
        require     => Database_grant["${user}@${host}/${name}"],
        subscribe   => Database[$name],
      }
```

but if you changed hostnamde, user and password you get error.
Command should be:
"/usr/bin/mysql -u${user} -p${password} -h${host}  ${name} < ${sql}"

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
