### ISSUE TITLE
Add option to exclude certain databases

### ISSUE THREAD

**Issue by robrwo** [puppetlabs/puppetlabs-mysql#449]
For our purposes, we don't need to backup the mysql, performance_schema or information_schema databases, so would like to exclude them from backups.

We can modify the [mysqlbackup.sh.erb](https://github.com/puppetlabs/puppetlabs-mysql/blob/master/templates/mysqlbackup.sh.erb) template with something like:

``` sh
mysql -s -r -N -e 'SHOW DATABASES' <% if ! @excludedatabases.empty? %> | grep -v '^\(<% @excludedatabases.join('|') %>)$' <% end %> | while read dbname
```

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
