### ISSUE TITLE
mysql_database odd ensure behaviour

### ISSUE THREAD

**Issue by dcarley** [puppetlabs/puppetlabs-mysql#458]
Specifying a `mysql_database` resource with no params (including `ensure`) results in nothing being created:

```
root@mysql-master-1:~# puppet apply --modulepath /var/govuk/puppet/vendor/modules
mysql_database { 'ohai': }
Notice: Finished catalog run in 0.96 seconds
```

But if a `charset` param (or `ensure` for that matter) is passed then it is:

```
root@mysql-master-1:~# puppet apply --modulepath /var/govuk/puppet/vendor/modules
mysql_database { 'ohai':
  charset => 'utf8',
}
Notice: /Stage[main]//Mysql_database[ohai]/ensure: created
Notice: Finished catalog run in 1.53 seconds
```

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
