### ISSUE TITLE
mysql_grant resource title confusion

### ISSUE THREAD

**Issue by dcarley** [puppetlabs/puppetlabs-mysql#460]
The user interface for `mysql_grant` is a bit confusing in the regard that the resource title must match the `user` and `table` params. If they don't match, then resources will still be created, but not idempotently. See #314 and the linked issues/PRs for example.

Although the README is clear about the requirements, it seems that a nicer user interface might be possible. What do you think about either of the following?
- Composite `namevar`
  
  The reason the resource title is significant is because `self.instances` uses it to pre-construct a hash of the existing resources. These have to have a resource title with some kind of canonical representation.
  
  Would `title_pattern` and ditching the duplicate `user` and `table` params work? I'm a bit rusty and it seems that the documentation about that area still is too.
- Validate title
  
  Validating the resource title against the `user` and `table` params would allow it to fail fast if there was a mismatch that could affect idempotency. Which should be a bit more user friendly, at the cost of still duplicating the information.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
