### ISSUE TITLE
mysql_user with unhashed password for hiera?

### ISSUE THREAD

**Issue by jmswick** [puppetlabs/puppetlabs-mysql#473]
Hello,
I'm wondering if it would be possible to expand the mysql_user provider to be able to accept an unhashed password so that it would be possible to define a mysql user for a database solely within hiera without also needing to specify the mysql password hash.  This is so that the password could be specified in a different hiera value and use the hiera lookup function to retrieve it.

The following example yaml would be my 'desired' dataset in hiera for creating my database (with the real passwords encrypted with eyaml):

```

---
classes:
  - mysql::server
  - mycustom_app
mysql::server::remove_default_accounts: true
mysql::server::root_password: my_db_root_pw
mysql::server::databases:
  myapps_db:
    ensure: present
mysql::server::users:
  'mydb_user@%':
    password: "%{hiera('mydb_user::password')}"
mysql::server::grants:
  'mydb_user@%/myapps_db.*':
    privileges: all
    table: 'myapps_db.*'
    user: 'mydb_user@%'
mycustom_app::db_user: mydb_user
mycustom_app::db_pass: "%{hiera('mydb_user::password')}"
mydb_user::password: mydb_user_password
```

With the current mysql_user provider, I'd have to store a 2nd value in hiera for the hashed mysql password, or create a create_resources wrapper class to hash the password before passing the parameters to mysql_user.  Either solution is  reasonable, but is a duplication of data or redundant effort in my opinion.

I started looking at the provider myself, but I'm unsure if you could call a custom puppet function from with in the custom provider.

Thank you.

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
