### ISSUE TITLE
mysqldump: Got error: 1102: Incorrect database name ' ' when selecting the database

### ISSUE THREAD

**Issue by kbotnen** [puppetlabs/puppetlabs-mysql#478]
mysqldump: Got error: 1102: Incorrect database name ' ' when selecting the database

due to newlines and spacing issues in the generated usr/local/sbin/mysqlbackup.sh script.

It seems to be a problem with the templatefile mysqlbackup.sh.erb (https://github.com/puppetlabs/puppetlabs-mysql/blob/master/templates/mysqlbackup.sh.erb)

Line 56,57 and 58 can be changed to: https://gist.github.com/kbotnen/9304226, line 56.

maybe line 45, 46, 47 should be treated similar.
- Kristian

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
